.TH pcompact 8 "September 2012" "@PRODUCT_NAME_SHORT@"
.SH NAME
\fBpcompact\fR \- utility for compacting Container virtual disks
.SH SYNOPSIS
\fBpcompact\fR [-v] [-n] [-s] [-t \fItimeout[s|m|h]\fR] [-DfR]
.SH DESCRIPTION
Remove unused blocks from Container virtual disks, increasing free disk space on the server.
.SH OPTIONS
.TP
\fB-v\fR
Increase the command output verbosity. Multiple -v options can be specified to produce a more verbose output.
.TP
\fB-q\fR
Do not print non-error messages to the console.
.TP
\fB-n\fR
Display the actions the command will execute, without actually compacting disks.
.TP
\fB-s\fR
Stop the command execution after compacting the first disk.
.TP
\fB-t\fR
\fItimeout[s|m|h]\fR
.br
Terminate the command after the specified \fItimeout\fR in \fIs\fReconds, \fIm\fRinutes or \fIh\fRours.
.TP
\fB-D\fR
Defragment file system only.
.SH SEE ALSO
.BR pcompact.conf (5)
.SH COPYRIGHT
.br
Copyright (c) 2011-2017, Parallels International GmbH. All rights reserved.
.br
Copyright (c) 2017-2022, Virtuozzo International GmbH. All rights reserved.
