.TH pcompact.conf 5 "September 2012" "OpenVZ"
.SH NAME
Configuration file for the \fBpcompact\fR utility.
.SH SYNOPSIS
/etc/vz/pcompact.conf
.SH DESCRIPTION
This configuration file is used by the \fBpcompact\fR utility to compact Container virtual disks.
.SS Parameters
.IP \fBTHRESHOLD\fR=\fInumber\fR
Compact the virtual disk if unused space on it exceeds \fBTHRESHOLD\fR percent of the ploop size.
.IP \fBDELTA\fR=\fInumber\fR
Reduce disk space to be compacted by \fBDELTA\fR percent of the ploop size.
.IP \fBDEFRAG\fR=\fIyes|no\fR
Perform or skip file system defragmentation.
.SH SEE ALSO
.BR pcompact (8)
.SH COPYRIGHT
Copyright (c) 2011-2016, Parallels IP Holdings GmbH. All rights reserved. 
